---
- name: Install and start Apache HTTPD
  hosts: awx
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true